theme: jekyll-theme-time-machine
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge